spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.100.89.227:3306/kxj_database?useUnicode=true&characterEncoding=utf8
#    url: jdbc:mysql://192.168.10.100:3306/kxj_database?useUnicode=true&characterEncoding=utf8
    username: root
    password: Abcd_12345678
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
server:
  port: 80
logging:
  level:
    root: WARN
#    root: DEBUG
    org.springframework.web: DEBUG
  file:
    name: web_log
#imagepath: E:\shenshuyinweb\PortalWebsiteSystem\images\
imagepath: /enterprise_website/images/